apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-rb
subjects:
- kind: ServiceAccount
  name: my-service-account
roleRef:
  kind: ClusterRole
  name: secret-cluster-role
  apiGroup: rbac.authorization.k8s.io 
